// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrymKrJQ58aA2t4VjNfkqL-j36YoQTbUM',
    appId: '1:844740453023:web:34acf253eb0151ab6378aa',
    messagingSenderId: '844740453023',
    projectId: 'metro-structure',
    authDomain: 'metro-structure.firebaseapp.com',
    storageBucket: 'metro-structure.firebasestorage.app',
    measurementId: 'G-QK35KPH568',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG9ip08x6FifLzn0hqLhWYBqvRKmjvz-Y',
    appId: '1:844740453023:android:b87b202a647ec2c96378aa',
    messagingSenderId: '844740453023',
    projectId: 'metro-structure',
    storageBucket: 'metro-structure.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnCAzMT_XKptLui_OidF6ng4-TeUYZhEY',
    appId: '1:844740453023:ios:89644aab2c7aa7496378aa',
    messagingSenderId: '844740453023',
    projectId: 'metro-structure',
    storageBucket: 'metro-structure.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnCAzMT_XKptLui_OidF6ng4-TeUYZhEY',
    appId: '1:844740453023:ios:89644aab2c7aa7496378aa',
    messagingSenderId: '844740453023',
    projectId: 'metro-structure',
    storageBucket: 'metro-structure.firebasestorage.app',
    iosBundleId: 'com.example.basicFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrymKrJQ58aA2t4VjNfkqL-j36YoQTbUM',
    appId: '1:844740453023:web:e740198e231be7fc6378aa',
    messagingSenderId: '844740453023',
    projectId: 'metro-structure',
    authDomain: 'metro-structure.firebaseapp.com',
    storageBucket: 'metro-structure.firebasestorage.app',
    measurementId: 'G-CFYVM9E77E',
  );
}
